---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-gerh-co-uk-staging
  namespace: traefik # Needs to be namespace of service
spec:
  secretName: traefik-gerh-co-uk-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "traefik.gerh.co.uk"
  dnsNames:
    - "traefik.gerh.co.uk"
